---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs/status
  verbs:
  - get
  - patch
  - update
