# This rule is not used by the project switch-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vulcan.vulcan resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: switch-controller
    app.kubernetes.io/managed-by: kustomize
  name: switchconfig-viewer-role
rules:
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs/status
  verbs:
  - get
