# This rule is not used by the project switch-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vulcan.vulcan.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: switch-controller
    app.kubernetes.io/managed-by: kustomize
  name: switchconfig-admin-role
rules:
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs
  verbs:
  - '*'
- apiGroups:
  - vulcan.vulcan
  resources:
  - switchconfigs/status
  verbs:
  - get
